title: "Site Title"
email: yourEmail@mail.com
description: >- # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "/Mysite" # the subpath of your site, MANDATORY FOR download.sh to work !
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository:
twitter:
github:

header_image: assets/Profile_perso.jpg

google_analytics:
comments: false
disqus:

author: Your name
author_bio: >-
  Yep

author_pic:

paginate: 20
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Your name
      avatar: assets/profile-sm.png
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
  - scope:
      path: ""
      type: journals
    values:
      layout: journal-entry
      content-type: journals

collections:
  pages:
    output: true
    permalink: /:title
#   notes:
#     output: true
#     permalink: /notes/:title
#   journals:
#     output: true
#     permalink: /journals/:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
